In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re

%matplotlib inline
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (7.0, 4.5)
plt.rcParams['font.size'] = 9
#plt.rcParams['figure.titlesize'] = 10
plt.rcParams['axes.titlesize'] = 10
plt.rcParams['axes.labelsize'] = 9
plt.rcParams['legend.fontsize'] = 8
plt.rcParams['xtick.labelsize'] = 8
plt.rcParams['ytick.labelsize'] = 8
plt.rcParams['axes.formatter.useoffset'] = False
plt.rcParams['xtick.major.size'] = 0
plt.rcParams['ytick.major.size'] = 0

In [2]:
raw_data = pd.read_csv("data/Indicators.csv")

In [3]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5656458 entries, 0 to 5656457
Data columns (total 6 columns):
CountryName      object
CountryCode      object
IndicatorName    object
IndicatorCode    object
Year             int64
Value            float64
dtypes: float64(1), int64(1), object(4)
memory usage: 302.1+ MB

In [4]:
chosen_indicators = ['IP.JRN.ARTC.SC', 'SP.DYN.LE00.IN' ]
df_indicators = raw_data[raw_data.IndicatorCode.isin(chosen_indicators)]

In [6]:
df_indicators.head()

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
1093546,East Asia & Pacific (all income levels),EAS,Scientific and technical journal articles,IP.JRN.ARTC.SC,1981,36706
1094007,East Asia & Pacific (developing only),EAP,Scientific and technical journal articles,IP.JRN.ARTC.SC,1981,1100
1094325,Euro area,EMU,Scientific and technical journal articles,IP.JRN.ARTC.SC,1981,70894
1094606,Europe & Central Asia (all income levels),ECS,Scientific and technical journal articles,IP.JRN.ARTC.SC,1981,124958
1095276,European Union,EUU,Scientific and technical journal articles,IP.JRN.ARTC.SC,1981,117952

In [3]:
df_ip = raw_data[raw_data.IndicatorCode == 'IP.JRN.ARTC.SC']
df_ip_1990= df_ip[df_ip.Year > 1990]

In [20]:
newDict = {}
newDict["Year"] = df_ip_1990["Year"]
newDict['IP.JRN.ARTC.SC'] = df_ip_1990["Value"]
newDict["CountryName"] = df_ip_1990["CountryName"]
newDict["CountryCode"] = df_ip_1990["CountryCode"]

In [21]:
pd.DataFrame(newDict)

,CountryCode,CountryName,IP.JRN.ARTC.SC,Year
1998367,ARB,Arab World,3244.567607,1991
1998715,CSS,Caribbean small states,138.879505,1991
1999033,CEB,Central Europe and the Baltics,11287.566323,1991
1999431,EAS,East Asia & Pacific (all income levels),64227.247148,1991
2000029,EAP,East Asia & Pacific (developing only),7144.861040,1991
2000477,EMU,Euro area,101917.292488,1991
2000866,ECS,Europe & Central Asia (all income levels),176552.261426,1991
2001408,ECA,Europe & Central Asia (developing only),2855.269784,1991
2001848,EUU,European Union,163997.900014,1991
2002208,FCS,Fragile and conflict affected situations,585.098381,1991
2002578,HPC,Heavily indebted poor countries (HIPC),738.912003,1991
2003007,HIC,High income,458576.428249,1991
2003793,OEC,High income: OECD,447431.089125,1991
2004220,LCN,Latin America & Caribbean (all income levels),7090.451982,1991
2004834,LAC,Latin America & Caribbean (developing only),4262.224272,1991
2005211,LDC,Least developed countries: UN classification,720.702777,1991
2005814,LMY,Low & middle income,31048.289324,1991
2006371,LIC,Low income,527.289802,1991
2006999,LMC,Lower middle income,13687.569674,1991
2007375,MEA,Middle East & North Africa (all income levels),8215.586501,1991
2007952,MNA,Middle East & North Africa (developing only),2294.898948,1991
2008569,MIC,Middle income,30494.453926,1991
2008971,NAC,North America,216960.082920,1991
2009418,OED,OECD members,449357.145042,1991
2009832,OSS,Other small states,94.010542,1991
2010142,PSS,Pacific island small states,33.790784,1991
2010483,SST,Small states,272.866667,1991
2011108,SAS,South Asia,10041.836857,1991
2011534,SSF,Sub-Saharan Africa (all income levels),4462.536421,1991
2012130,SSA,Sub-Saharan Africa (developing only),4460.570827,1991
...,...,...,...,...
5177846,LCA,St. Lucia,0.400000,2011
5178633,VCT,St. Vincent and the Grenadines,0.000000,2011
5179488,SDN,Sudan,69.300000,2011
5180036,SUR,Suriname,1.400000,2011
5180831,SWZ,Swaziland,12.100000,2011
5181576,SWE,Sweden,9472.900000,2011
5182323,CHE,Switzerland,10018.600000,2011
5182977,SYR,Syrian Arab Republic,110.000000,2011
5183848,TJK,Tajikistan,18.400000,2011
5184770,TZA,Tanzania,121.100000,2011
5185783,THA,Thailand,2304.000000,2011
5187239,TGO,Togo,8.200000,2011
5187992,TON,Tonga,0.500000,2011
5188516,TTO,Trinidad and Tobago,60.200000,2011
5189374,TUN,Tunisia,1015.500000,2011
5190411,TUR,Turkey,8328.400000,2011
5191057,TKM,Turkmenistan,0.500000,2011
5191352,TUV,Tuvalu,0.000000,2011
5192245,UGA,Uganda,158.200000,2011
5193260,UKR,Ukraine,1726.900000,2011
5193855,ARE,United Arab Emirates,323.500000,2011
5194525,GBR,United Kingdom,46035.400000,2011
5195984,URY,Uruguay,290.400000,2011
5196768,UZB,Uzbekistan,140.900000,2011
5197508,VUT,Vanuatu,4.700000,2011
5198225,VEN,"Venezuela, RB",302.100000,2011
5199125,VNM,Vietnam,431.500000,2011
5200513,YEM,"Yemen, Rep.",33.300000,2011
5201356,ZMB,Zambia,59.600000,2011
5202185,ZWE,Zimbabwe,62.900000,2011

In [24]:
df_ip_n = raw_data[raw_data.IndicatorCode == 'SP.DYN.LE00.IN']
df_ip_n_1990 = df_ip_n[df_ip_n.Year > 1990]
df_ip_n_1990.head()

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
1998219,Arab World,ARB,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,1991,65.000099
1998573,Caribbean small states,CSS,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,1991,69.040605
1998924,Central Europe and the Baltics,CEB,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,1991,70.572608
1999284,East Asia & Pacific (all income levels),EAS,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,1991,69.423315
1999763,East Asia & Pacific (developing only),EAP,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,1991,68.420665

In [23]:
newDict['SP.DYN.LE00.IN'] = df_ip_n_1990["Value"]
pd.DataFrame(newDict)

,CountryCode,CountryName,IP.JRN.ARTC.SC,SP.DYN.LE00.IN,Year
1998219,NaN,NaN,NaN,65.000099,NaN
1998367,ARB,Arab World,3244.567607,NaN,1991
1998573,NaN,NaN,NaN,69.040605,NaN
1998715,CSS,Caribbean small states,138.879505,NaN,1991
1998924,NaN,NaN,NaN,70.572608,NaN
1999033,CEB,Central Europe and the Baltics,11287.566323,NaN,1991
1999284,NaN,NaN,NaN,69.423315,NaN
1999431,EAS,East Asia & Pacific (all income levels),64227.247148,NaN,1991
1999763,NaN,NaN,NaN,68.420665,NaN
2000029,EAP,East Asia & Pacific (developing only),7144.861040,NaN,1991
2000323,NaN,NaN,NaN,76.023174,NaN
2000477,EMU,Euro area,101917.292488,NaN,1991
2000727,NaN,NaN,NaN,71.980860,NaN
2000866,ECS,Europe & Central Asia (all income levels),176552.261426,NaN,1991
2001155,NaN,NaN,NaN,67.699611,NaN
2001408,ECA,Europe & Central Asia (developing only),2855.269784,NaN,1991
2001694,NaN,NaN,NaN,74.967504,NaN
2001848,EUU,European Union,163997.900014,NaN,1991
2002072,NaN,NaN,NaN,55.689535,NaN
2002208,FCS,Fragile and conflict affected situations,585.098381,NaN,1991
2002432,NaN,NaN,NaN,49.693621,NaN
2002578,HPC,Heavily indebted poor countries (HIPC),738.912003,NaN,1991
2002851,NaN,NaN,NaN,74.500023,NaN
2003007,HIC,High income,458576.428249,NaN,1991
2003231,NaN,NaN,NaN,70.074133,NaN
2003636,NaN,NaN,NaN,75.816134,NaN
2003793,OEC,High income: OECD,447431.089125,NaN,1991
2004064,NaN,NaN,NaN,68.104696,NaN
2004220,LCN,Latin America & Caribbean (all income levels),7090.451982,NaN,1991
2004558,NaN,NaN,NaN,67.402612,NaN
...,...,...,...,...,...
5514042,NaN,NaN,NaN,70.990000,NaN
5514588,NaN,NaN,NaN,48.937927,NaN
5515327,NaN,NaN,NaN,81.704878,NaN
5515964,NaN,NaN,NaN,82.748780,NaN
5516405,NaN,NaN,NaN,74.715780,NaN
5517155,NaN,NaN,NaN,69.400171,NaN
5518021,NaN,NaN,NaN,64.291829,NaN
5518938,NaN,NaN,NaN,74.246927,NaN
5519652,NaN,NaN,NaN,67.522366,NaN
5520232,NaN,NaN,NaN,59.132366,NaN
5520866,NaN,NaN,NaN,72.640341,NaN
5521466,NaN,NaN,NaN,70.305293,NaN
5522056,NaN,NaN,NaN,73.646341,NaN
5522977,NaN,NaN,NaN,75.175951,NaN
5523663,NaN,NaN,NaN,65.456561,NaN
5524727,NaN,NaN,NaN,57.767683,NaN
5525658,NaN,NaN,NaN,71.159512,NaN
5526399,NaN,NaN,NaN,77.195634,NaN
5526979,NaN,NaN,NaN,80.956098,NaN
5527632,NaN,NaN,NaN,78.841463,NaN
5528269,NaN,NaN,NaN,76.836195,NaN
5528894,NaN,NaN,NaN,68.227585,NaN
5529616,NaN,NaN,NaN,71.669244,NaN
5530269,NaN,NaN,NaN,74.074415,NaN
5530973,NaN,NaN,NaN,75.756488,NaN
5531448,NaN,NaN,NaN,79.624390,NaN
5531812,NaN,NaN,NaN,73.203341,NaN
5532394,NaN,NaN,NaN,63.583512,NaN
5533191,NaN,NaN,NaN,59.237366,NaN
5533981,NaN,NaN,NaN,55.633000,NaN

In [5]:
year = 1989
raw_data_1990 = raw_data[raw_data.Year > year]
raw_data_1990.head()

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
1880402,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,1990,75.447507
1880403,Arab World,ARB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,1990,58.680636
1880404,Arab World,ARB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,1990,91.842354
1880405,Arab World,ARB,Access to non-solid fuel (% of population),EG.NSF.ACCS.ZS,1990,74.223510
1880406,Arab World,ARB,"Adjusted net enrolment rate, primary, both sex...",SE.PRM.TENR,1990,72.104721

In [6]:
test = raw_data_1990.pivot_table('Value', ['Year','CountryName', 'CountryCode'], 'IndicatorCode'  )

In [7]:
test

IndicatorCode                              AG.AGR.TRAC.NO  AG.CON.FERT.PT.ZS  \
Year CountryName              CountryCode
1990 Afghanistan              AFG                     120                NaN
     Albania                  ALB                   12300                NaN
     Algeria                  DZA                   91426                NaN
     American Samoa           ASM                      11                NaN
     Andorra                  ADO                     NaN                NaN
     Angola                   AGO                     NaN                NaN
     Antigua and Barbuda      ATG                     NaN                NaN
     Arab World               ARB                  383795                NaN
     Argentina                ARG                  264500                NaN
     Armenia                  ARM                     NaN                NaN
     Aruba                    ABW                     NaN                NaN
     Australia                AUS                     NaN                NaN
     Austria                  AUT                  338482                NaN
     Azerbaijan               AZE                     NaN                NaN
     Bahamas, The             BHS                     113                NaN
     Bahrain                  BHR                       9                NaN
     Bangladesh               BGD                    2180                NaN
     Barbados                 BRB                     NaN                NaN
     Belarus                  BLR                     NaN                NaN
     Belgium                  BEL                     NaN                NaN
     Belize                   BLZ                     NaN                NaN
     Benin                    BEN                     155                NaN
     Bermuda                  BMU                      47                NaN
     Bhutan                   BTN                      50                NaN
     Bolivia                  BOL                    5200                NaN
     Bosnia and Herzegovina   BIH                     NaN                NaN
     Botswana                 BWA                    5900                NaN
     Brazil                   BRA                  728779                NaN
     Brunei Darussalam        BRN                     NaN                NaN
     Bulgaria                 BGR                   52375                NaN
...                                                   ...                ...
2015 Syrian Arab Republic     SYR                     NaN                NaN
     Tajikistan               TJK                     NaN                NaN
     Tanzania                 TZA                     NaN                NaN
     Thailand                 THA                     NaN                NaN
     Timor-Leste              TMP                     NaN                NaN
     Togo                     TGO                     NaN                NaN
     Tonga                    TON                     NaN                NaN
     Trinidad and Tobago      TTO                     NaN                NaN
     Tunisia                  TUN                     NaN                NaN
     Turkey                   TUR                     NaN                NaN
     Turkmenistan             TKM                     NaN                NaN
     Turks and Caicos Islands TCA                     NaN                NaN
     Tuvalu                   TUV                     NaN                NaN
     Uganda                   UGA                     NaN                NaN
     Ukraine                  UKR                     NaN                NaN
     United Arab Emirates     ARE                     NaN                NaN
     United Kingdom           GBR                     NaN                NaN
     United States            USA                     NaN                NaN
     Upper middle income      UMC                     NaN                NaN
     Uruguay                  URY                     NaN                NaN
     Uzbekistan               UZB                     NaN                NaN
     Vanuatu                  VUT                     NaN                NaN
     Venezuela, RB            VEN                     NaN                NaN
     Vietnam                  VNM                     NaN                NaN
     Virgin Islands (U.S.)    VIR                     NaN                NaN
     West Bank and Gaza       WBG                     NaN                NaN
     World                    WLD                     NaN                NaN
     Yemen, Rep.              YEM                     NaN                NaN
     Zambia                   ZMB                     NaN                NaN
     Zimbabwe                 ZWE                     NaN                NaN

IndicatorCode                              AG.CON.FERT.ZS  AG.LND.AGRI.K2  \
Year CountryName              CountryCode
1990 Afghanistan              AFG                     NaN          380400
     Albania                  ALB                     NaN           11210
     Algeria                  DZA                     NaN          386760
     American Samoa           ASM                     NaN              30
     Andorra                  ADO                     NaN             190
     Angola                   AGO                     NaN          574040
     Antigua and Barbuda      ATG                     NaN              90
     Arab World               ARB                     NaN         4772142
     Argentina                ARG                     NaN         1275650
     Armenia                  ARM                     NaN             NaN
     Aruba                    ABW                     NaN              20
     Australia                AUS                     NaN         4644810
     Austria                  AUT                     NaN           35000
     Azerbaijan               AZE                     NaN             NaN
     Bahamas, The             BHS                     NaN             120
     Bahrain                  BHR                     NaN              80
     Bangladesh               BGD                     NaN          103860
     Barbados                 BRB                     NaN             190
     Belarus                  BLR                     NaN             NaN
     Belgium                  BEL                     NaN             NaN
     Belize                   BLZ                     NaN            1260
     Benin                    BEN                     NaN           22700
     Bermuda                  BMU                     NaN               3
     Bhutan                   BTN                     NaN            4540
     Bolivia                  BOL                     NaN          354550
     Bosnia and Herzegovina   BIH                     NaN             NaN
     Botswana                 BWA                     NaN          260210
     Brazil                   BRA                     NaN         2416080
     Brunei Darussalam        BRN                     NaN             110
     Bulgaria                 BGR                     NaN           61590
...                                                   ...             ...
2015 Syrian Arab Republic     SYR                     NaN             NaN
     Tajikistan               TJK                     NaN             NaN
     Tanzania                 TZA                     NaN             NaN
     Thailand                 THA                     NaN             NaN
     Timor-Leste              TMP                     NaN             NaN
     Togo                     TGO                     NaN             NaN
     Tonga                    TON                     NaN             NaN
     Trinidad and Tobago      TTO                     NaN             NaN
     Tunisia                  TUN                     NaN             NaN
     Turkey                   TUR                     NaN             NaN
     Turkmenistan             TKM                     NaN             NaN
     Turks and Caicos Islands TCA                     NaN             NaN
     Tuvalu                   TUV                     NaN             NaN
     Uganda                   UGA                     NaN             NaN
     Ukraine                  UKR                     NaN             NaN
     United Arab Emirates     ARE                     NaN             NaN
     United Kingdom           GBR                     NaN             NaN
     United States            USA                     NaN             NaN
     Upper middle income      UMC                     NaN             NaN
     Uruguay                  URY                     NaN             NaN
     Uzbekistan               UZB                     NaN             NaN
     Vanuatu                  VUT                     NaN             NaN
     Venezuela, RB            VEN                     NaN             NaN
     Vietnam                  VNM                     NaN             NaN
     Virgin Islands (U.S.)    VIR                     NaN             NaN
     West Bank and Gaza       WBG                     NaN             NaN
     World                    WLD                     NaN             NaN
     Yemen, Rep.              YEM                     NaN             NaN
     Zambia                   ZMB                     NaN             NaN
     Zimbabwe                 ZWE                     NaN             NaN

IndicatorCode                              AG.LND.AGRI.ZS  AG.LND.ARBL.HA  \
Year CountryName              CountryCode
1990 Afghanistan              AFG               58.266703         7910000
     Albania                  ALB               40.912409          579000
     Algeria                  DZA               16.238548         7081000
     American Samoa           ASM               15.000000            1000
     Andorra                  ADO               40.425532            2000
     Angola                   AGO               46.044758         2900000
     Antigua and Barbuda      ATG               20.454545            4000
     Arab World               ARB               35.027489             NaN
     Argentina                ARG               46.612879        26575000
     Armenia                  ARM                     NaN             NaN
     Aruba                    ABW               11.111111            2000
     Australia                AUS               60.461190        47900000
     Austria                  AUT               42.383144         1426000
     Azerbaijan               AZE                     NaN             NaN
     Bahamas, The             BHS                1.198801            8000
     Bahrain                  BHR               11.594203            2000
     Bangladesh               BGD               79.787970         9456000
     Barbados                 BRB               44.186047           16000
     Belarus                  BLR                     NaN             NaN
     Belgium                  BEL                     NaN             NaN
     Belize                   BLZ                5.523893           52000
     Benin                    BEN               20.131252         1615000
     Bermuda                  BMU                6.000000             300
     Bhutan                   BTN                9.716842          135000
     Bolivia                  BOL               32.728699         2100000
     Bosnia and Herzegovina   BIH                     NaN             NaN
     Botswana                 BWA               45.914280          420000
     Brazil                   BRA               28.906910        50681000
     Brunei Darussalam        BRN                2.087287            2000
     Bulgaria                 BGR               55.672060         3856000
...                                                   ...             ...
2015 Syrian Arab Republic     SYR                     NaN             NaN
     Tajikistan               TJK                     NaN             NaN
     Tanzania                 TZA                     NaN             NaN
     Thailand                 THA                     NaN             NaN
     Timor-Leste              TMP                     NaN             NaN
     Togo                     TGO                     NaN             NaN
     Tonga                    TON                     NaN             NaN
     Trinidad and Tobago      TTO                     NaN             NaN
     Tunisia                  TUN                     NaN             NaN
     Turkey                   TUR                     NaN             NaN
     Turkmenistan             TKM                     NaN             NaN
     Turks and Caicos Islands TCA                     NaN             NaN
     Tuvalu                   TUV                     NaN             NaN
     Uganda                   UGA                     NaN             NaN
     Ukraine                  UKR                     NaN             NaN
     United Arab Emirates     ARE                     NaN             NaN
     United Kingdom           GBR                     NaN             NaN
     United States            USA                     NaN             NaN
     Upper middle income      UMC                     NaN             NaN
     Uruguay                  URY                     NaN             NaN
     Uzbekistan               UZB                     NaN             NaN
     Vanuatu                  VUT                     NaN             NaN
     Venezuela, RB            VEN                     NaN             NaN
     Vietnam                  VNM                     NaN             NaN
     Virgin Islands (U.S.)    VIR                     NaN             NaN
     West Bank and Gaza       WBG                     NaN             NaN
     World                    WLD                     NaN             NaN
     Yemen, Rep.              YEM                     NaN             NaN
     Zambia                   ZMB                     NaN             NaN
     Zimbabwe                 ZWE                     NaN             NaN

IndicatorCode                              AG.LND.ARBL.HA.PC  AG.LND.ARBL.ZS  \
Year CountryName              CountryCode
1990 Afghanistan              AFG                   0.655476       12.115921
     Albania                  ALB                   0.176173       21.131387
     Algeria                  DZA                   0.273267        2.973037
     American Samoa           ASM                   0.021257        5.000000
     Andorra                  ADO                   0.036690        4.255319
     Angola                   AGO                   0.260607        2.326141
     Antigua and Barbuda      ATG                   0.064614        9.090909
     Arab World               ARB                   0.236243        3.848300
     Argentina                ARG                   0.811953        9.710636
     Armenia                  ARM                        NaN             NaN
     Aruba                    ABW                   0.032181       11.111111
     Australia                AUS                   2.806898        6.235112
     Austria                  AUT                   0.185729       17.268104
     Azerbaijan               AZE                        NaN             NaN
     Bahamas, The             BHS                   0.031209        0.799201
     Bahrain                  BHR                   0.004033        2.898551
     Bangladesh               BGD                   0.089222       72.643466
     Barbados                 BRB                   0.061450       37.209302
     Belarus                  BLR                        NaN             NaN
     Belgium                  BEL                        NaN             NaN
     Belize                   BLZ                   0.277256        2.279702
     Benin                    BEN                   0.322918       14.322455
     Bermuda                  BMU                   0.005057        6.000000
     Bhutan                   BTN                   0.252098        2.889369
     Bolivia                  BOL                   0.306290        1.938521
     Bosnia and Herzegovina   BIH                        NaN             NaN
     Botswana                 BWA                   0.304389        0.741094
     Brazil                   BRA                   0.336990        6.063670
     Brunei Darussalam        BRN                   0.007784        0.379507
     Bulgaria                 BGR                   0.442289       34.854922
...                                                      ...             ...
2015 Syrian Arab Republic     SYR                        NaN             NaN
     Tajikistan               TJK                        NaN             NaN
     Tanzania                 TZA                        NaN             NaN
     Thailand                 THA                        NaN             NaN
     Timor-Leste              TMP                        NaN             NaN
     Togo                     TGO                        NaN             NaN
     Tonga                    TON                        NaN             NaN
     Trinidad and Tobago      TTO                        NaN             NaN
     Tunisia                  TUN                        NaN             NaN
     Turkey                   TUR                        NaN             NaN
     Turkmenistan             TKM                        NaN             NaN
     Turks and Caicos Islands TCA                        NaN             NaN
     Tuvalu                   TUV                        NaN             NaN
     Uganda                   UGA                        NaN             NaN
     Ukraine                  UKR                        NaN             NaN
     United Arab Emirates     ARE                        NaN             NaN
     United Kingdom           GBR                        NaN             NaN
     United States            USA                        NaN             NaN
     Upper middle income      UMC                        NaN             NaN
     Uruguay                  URY                        NaN             NaN
     Uzbekistan               UZB                        NaN             NaN
     Vanuatu                  VUT                        NaN             NaN
     Venezuela, RB            VEN                        NaN             NaN
     Vietnam                  VNM                        NaN             NaN
     Virgin Islands (U.S.)    VIR                        NaN             NaN
     West Bank and Gaza       WBG                        NaN             NaN
     World                    WLD                        NaN             NaN
     Yemen, Rep.              YEM                        NaN             NaN
     Zambia                   ZMB                        NaN             NaN
     Zimbabwe                 ZWE                        NaN             NaN

IndicatorCode                              AG.LND.CREL.HA  AG.LND.CROP.ZS  \
Year CountryName              CountryCode
1990 Afghanistan              AFG                 2253000        0.199124
     Albania                  ALB                  321000        4.562044
     Algeria                  DZA                 2365999        0.232603
     American Samoa           ASM                     NaN       10.000000
     Andorra                  ADO                     NaN             NaN
     Angola                   AGO                  774281        0.401059
     Antigua and Barbuda      ATG                      21        2.272727
     Arab World               ARB                26065693        0.415931
     Argentina                ARG                 9014945        0.372713
     Armenia                  ARM                     NaN             NaN
     Aruba                    ABW                     NaN             NaN
     Australia                AUS                13428753        0.023561
     Austria                  AUT                  948437        0.956648

In [42]:
test.to_csv("test.csv")

In [43]:
test.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6421 entries, (1990, Afghanistan, AFG) to (2015, Zimbabwe, ZWE)
Columns: 1344 entries, 2005 PPP conversion factor, GDP (LCU per international $) to Youth literacy rate, population 15-24 years, male (%)
dtypes: float64(1344)
memory usage: 65.9+ MB

In [45]:
"Equity" in raw_data.IndicatorName

False

In [46]:
countryData = pd.read_csv("data/Country.csv")

In [47]:
countryData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 247 entries, 0 to 246
Data columns (total 31 columns):
CountryCode                                   247 non-null object
ShortName                                     247 non-null object
TableName                                     247 non-null object
LongName                                      247 non-null object
Alpha2Code                                    244 non-null object
CurrencyUnit                                  214 non-null object
SpecialNotes                                  164 non-null object
Region                                        214 non-null object
IncomeGroup                                   214 non-null object
Wb2Code                                       246 non-null object
NationalAccountsBaseYear                      205 non-null object
NationalAccountsReferenceYear                 54 non-null object
SnaPriceValuation                             198 non-null object
LendingCategory                               144 non-null object
OtherGroups                                   59 non-null object
SystemOfNationalAccounts                      214 non-null object
AlternativeConversionFactor                   47 non-null object
PppSurveyYear                                 191 non-null object
BalanceOfPaymentsManualInUse                  181 non-null object
ExternalDebtReportingStatus                   124 non-null object
SystemOfTrade                                 200 non-null object
GovernmentAccountingConcept                   161 non-null object
ImfDataDisseminationStandard                  183 non-null object
LatestPopulationCensus                        213 non-null object
LatestHouseholdSurvey                         147 non-null object
SourceOfMostRecentIncomeAndExpenditureData    158 non-null object
VitalRegistrationComplete                     112 non-null object
LatestAgriculturalCensus                      142 non-null object
LatestIndustrialData                          113 non-null float64
LatestTradeData                               186 non-null float64
LatestWaterWithdrawalData                     180 non-null float64
dtypes: float64(3), object(28)
memory usage: 61.8+ KB

In [49]:
df_country = pd.DataFrame()